trunk/inventory/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic import list_detail, create_update
from inventory.models import *

vm_dict = {
	'queryset':VirtualMachine.objects.all(),
	'template_object_name' : "vm",
}

dstore_dict = {
	'queryset':DataStore.objects.order_by('name'),
	'template_object_name' : "dstore",
}

host_dict = {
	'queryset':VMHost.objects.order_by('name'),
	'template_object_name' : "vmhost",
}

server_dict = {
	'queryset':Server.objects.order_by('name'),
	'template_object_name' : "server",
}


urlpatterns = patterns('',
	url(r'^server/list/$', list_detail.object_list, dict(server_dict,template_name='server_list.html'), name='server-list'),
	url(r'^server/create', 'inventory.views.newServer', name='new-server'),
	url(r'^server/view/(?P<object_id>[-\w]+)/', list_detail.object_detail, dict(server_dict, template_name='server_detail.html'), name='server-detail'),
	url(r'^server/edit/(?P<server_id>[-\w]+)', 'inventory.views.editServer', name='edit-server'),
	
	url(r'^vm/$', list_detail.object_list, dict(vm_dict,template_name='vm_list.html'), name='virtual'),	
	url(r'^vm/(?P<object_id>[-\w]+)/', list_detail.object_detail, dict(vm_dict, template_name='vm_detail.html'), name='vm-detail'),
	
	url(r'^datastore/list/$', list_detail.object_list, dict(dstore_dict,template_name='datastore_list.html'), name='datastore-list'),
	url(r'^datastore/(?P<object_id>[-\w]+)/', list_detail.object_detail, dict(dstore_dict, template_name='datastore.html'), name='datastore'),
	
	url(r'^host/list/$', list_detail.object_list, dict(host_dict,template_name='host_list.html'), name='host-list'),
	url(r'^host/(?P<object_id>[-\w]+)/', list_detail.object_detail, dict(host_dict, template_name='host.html'), name='host'),
)

trunk/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # index: homepage
    url(r'^$', 'inventory.views.homepage', name='homepage'),
	  url(r'^about/', 'django.views.generic.simple.direct_to_template', {'template': 'about.html'}, name='about'),
  	# inventory urls
  	url(r'^inventory/', include('inventory.urls')),

	
	# Static media 
	url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT,'show_indexes': True }),
)

trunk/inventory/models.py
from django.db import models
from django.forms import ModelForm

# Abstract class that other inventory items can inherit from
# http://stackoverflow.com/questions/1737017/django-auto-now-and-auto-now-add
class ISCNode(models.Model): 
    ROLE_CHOICES = (
        (u'dev',  u'Development'),
        (u'prod', u'Production'),
    )
    name       = models.CharField(max_length="30",unique=True)
    notes      = models.TextField(blank=True)
    role       = models.CharField(max_length=4, choices=ROLE_CHOICES, blank=True)
    
	# These fields are hidden from the administrative interface
    created    = models.DateTimeField(auto_now_add=True)
    modified   = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
      return ('system-display', (), {'object_id': self.id})

    class Meta:
        abstract = True	

# Child class of ISCNode for 'on-the-iron' servers
class Server(ISCNode):
    vendor      = models.ForeignKey('Vendor')
    capacityMB  = models.IntegerField()
    cpuCount    = models.PositiveSmallIntegerField()
    purchased   = models.DateTimeField(null=True, blank=True)
    sccTag      = models.CharField(max_length="80", null=True, blank=True)
    warranty    = models.DateTimeField(null=True, blank=True)
    po          = models.CharField(max_length="7", null=True, blank=True)
    


# Datastores can hold many VMHosts, by making 
# a separate class, we avoid typos
class DataStore(ISCNode):
    capacityMB           = models.IntegerField()
    freespaceMB          = models.IntegerField()
    usedMB               = models.IntegerField()
    percentUtilized      = models.IntegerField()
    filesystemVersion    = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)

    @staticmethod
    # https://docs.djangoproject.com/en/1.3/topics/db/managers/
    def create(name, capacityMB, freespaceMB, filesystemVersion):
        usedMB = int(capacityMB) - int(freespaceMB)
        if (usedMB > 0):
          percentUtilized = (usedMB/float(capacityMB))*100
        else:
          percentUtilized = 0
        return DataStore(name=name, capacityMB=capacityMB, freespaceMB=freespaceMB, filesystemVersion=filesystemVersion, usedMB=usedMB, percentUtilized=percentUtilized)


# VMHost can hold many VirtualMachines, by making 
# a separate class, we avoid typos
class VMHost(ISCNode):
    manufacturer = models.ForeignKey('Vendor')
    model        = models.CharField(max_length="30")
    cpuCount     = models.PositiveSmallIntegerField()
    cpuTotal     = models.PositiveSmallIntegerField()
    cpuUsage     = models.PositiveSmallIntegerField(editable=False)
    processor    = models.CharField(max_length="50")


# Child class of ISCNode
class VirtualMachine(ISCNode):
    powerState = models.NullBooleanField()
    cpuCount   = models.IntegerField()
    memoryMB   = models.IntegerField()
    host       = models.ForeignKey('VMHost')
    datastore  = models.ManyToManyField('DataStore')
    
    @staticmethod
    def create(name, powerState,cpuCount, memoryMB, host):
        return VirtualMachine(name=name, powerState=powerState,cpuCount=cpuCount, memoryMB=memoryMB, host=host)

# A class for Vendors, to avoid duplication
# or typos by manual entry
class Vendor(models.Model):
    name         = models.CharField(max_length="30")
    website      = models.CharField(max_length="100", blank=True)

    def __unicode__(self):
        return self.name

# IP addresses might not need their own class, but this 
# was a design consideration that would be another safeguard
# against assigning an IP that is already in use and to avoid typos
class IpAddress(models.Model):
    address = models.IPAddressField(unique=True)
    vm      = models.ForeignKey(VirtualMachine)

    def __unicode__(self):
        return self.address

trunk/inventory/forms.py
from django import forms
from inventory.models import Server


class NewServerForm(forms.ModelForm):
    class Meta:
        model = Server

class EditServerForm(forms.ModelForm):
    class Meta:
        model = Server

trunk/inventory/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import Context, loader, RequestContext
from django.http import HttpResponse, HttpResponseRedirect

from inventory.forms import NewServerForm, EditServerForm
from inventory.models import *

def homepage(request):
    vendor_list = Vendor.objects.all()
    server_list = Server.objects.all()
    vm_list = VirtualMachine.objects.all()
    return render_to_response(
	    "index.html",
		{'vendor_list': vendor_list, 'server_list':server_list, 'vm_list':vm_list}, 
		context_instance=RequestContext(request))

def newServer(request): 
    # If the form has been submitted...
    if request.method == 'POST': 
        # A form bound to the POST data
        form = NewServerForm(request.POST)
        # All validation rules pass
        if form.is_valid(): 
            form.save()
            # Redirect after POST
            return HttpResponseRedirect('/') 
    else:
        # An unbound form
        form = NewServerForm() 
    return render_to_response(
            'server_new.html', 
            { 'form': form,},  
            context_instance=RequestContext(request))
    
def editServer(request, server_id):
    # Which server will this form show?
    server = get_object_or_404(Server, pk=server_id)
    
    # If the form has been submitted...
    if request.method == 'POST': 
        # A form bound to the POST data
        form = EditServerForm(request.POST, instance=server)
        # All validation rules pass
        if form.is_valid(): 
            form.save()
            # Redirect after POST (to guard from accidentally reposting)
            return HttpResponseRedirect('/')
             
    # The form has not been submitted, it's a GET request 
    else:
        # A form that is bound to server data
        form = EditServerForm(instance=server) 
    return render_to_response(
            'server_edit.html', 
            { 'form': form, 'server_id':server.id},  
            context_instance=RequestContext(request))

trunk/inventory/templates/about.html
{% extends "base.html" %}

{% load pagination_tags %}
{% block title %}About{% endblock title%}

{% block content %}
   <p>This inventory system was designed to keep track of the various physical and virtual systems (regardless of their current use)
   that are under the care of an organization. The system was made using the 
   <a href="http://en.wikipedia.org/wiki/Python_(programming_language)#Name_and_neologisms" target="_new">
   Pythonic</a> framework  
   <a href="https://www.djangoproject.com/" target="_new">Django</a>.
   </p> 
   <p>The system expects to be populated by some csv files (assumed to be <a href="http://technet.microsoft.com/en-us/library/bb978526.aspx" target="_new">PowerShell</a> exports from <a href="http://www.vmware.com/products/vsphere/mid-size-and-enterprise-business/overview.html" target="_new">VSphere</a>) 
   which are arranged as follows:</p>
   <ul>
     <li><strong>DataStore.csv</strong> <br/> Name,CapacityMB,FreeSpaceMB,FileSystemVersion</li>
     <li><strong>VMHost.csv</strong> <br/> Name,Manufacturer,Model,NumCpu,CpuTotalMhz,CpuUsageMhz,ProcessorType</li>
     <li><strong>VirtualMachine.csv</strong><br/>Name,PowerState,NumCpu,MemoryMB,Notes,VMHost,Datastore</li>
     <li><strong>IpAddress.csv</strong><br/>Name,ip</li>
   </ul>
   <p>These files are assumed to be kept in the data subfolder of django django project. The script that reads the data files is part of the 
   svn project, and is located in the scripts subfolder of the django project. Since the vsphere data is 'read-only': every time the script 
   runs, it resets the tables associated with vsphere objects and then repopulates them entirely. 
   </p>
{% endblock content%}

trunk/inventory/templates/base.html
<!doctype html>
<html class="no-js" lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<link rel="stylesheet" href="/site_media/pre.css" type="text/css" />
  <link rel="stylesheet" href="/site_media/style.css" type="text/css" />
  <link rel="stylesheet" href="/site_media/post.css" type="text/css" />
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{% block title %}Distributed Systems Inventory{% endblock %}</title>

</head>

<body>

<div id="container">
<header>
<h1><a href="{% url homepage %}">Inventory</a></h1>
<div id="navigation">
<a href="{% url about %}">about</a>
<a href="{% url server-list %}">servers</a>
<a href="{% url virtual %}">virtual</a>
</div>

{% block subnav %}{% endblock subnav %}


</header>

    <div id="content">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% block content %}{% endblock content%}
        <hr/>
        
    </div>


<footer>&copy; isc (information systems and computing)</footer>
</div>

</body>
</html>

trunk/inventory/templates/contact.html
{% extends "base.html" %}

{% block content%}
<form action="/contact/" method="post">{% csrf_token %}
{{ form }}
<input type="submit" value="Submit" />
</form>
{% endblock content%}

trunk/inventory/templates/datastore.html
{% extends "base.html" %}

{% block title %}DataStore Detail{% endblock title %}

{% block subnav %}{% include "virtual_nav.html" %}{% endblock subnav %}

{% block content %}
  <script language="javascript" type="text/javascript" src="/site_media/js/jquery-1.7.1.js"></script>
	<script language="javascript" type="text/javascript" src="/site_media/js/jquery.flot.js"></script>
  <script language="javascript" type="text/javascript" src="/site_media/js/jquery.flot.pie.js"></script>
  <style type="text/css">
		div.graph{width: 56em;height: 300px;}
		label{display: block;padding-left: 1em;}
	</style>

<h1>{{ dstore.name }}</h1>
<small>datastore</small>

<table>
<tr><th>Property</th><th>Value</th></tr>
<tr><td>Name</td><td>{{ dstore.name }}</td></tr>
<tr><td>Capacity</td><td>{{ dstore.capacityMB }} MB</td></tr>
<tr><td>Free Space</td><td>{{ dstore.freespaceMB }} MB</td></tr>
<tr><td>File System Version</td><td>{{ dstore.filesystemVersion }}</td></tr>
<tr><td>Virtual Machines</td>
    <td><ul>{% for vm in dstore.virtualmachine_set.all %}
        <li><a href="{% url  vm-detail vm.id%}">{{ vm.name }}</a></li>{% endfor %}</ul
	</td></tr>
<tr><td></td><td align="right"><small>Last modified ({{dstore.created|date:"Y:z g:i a"}})</small></td></tr>
</table>
<div id="default" class="graph">Graph goes here</div>

<script type="text/javascript">
$(function () {
  var free = {{ dstore.freespaceMB }}
  var used = {{ dstore.capacityMB }} - free
	var d1 = [
    { label: "used",  data: used},
		{ label: "available",  data: free},  
  ];
                        
    $.plot($("#default"), d1, 
    {
         series: {
             pie: { 
                 show: true,
                 radius: 1,
                 label: {
                     show: true,
                     radius: 3/4,
                     formatter: function(label, series){
                         return '<div style="font-size:8pt;text-align:center;padding:2px;color:white;">'+label+'<br/>'+Math.round(series.percent)+'%</div>';
                     },
                     background: { opacity: 0.5 }
                 }
             }
         },
         legend: {
             show: false
         }
    });
});
</script>
{% endblock content %}

trunk/inventory/templates/datastore_list.html
{% extends "base.html" %}

{% block title %}Datastores{% endblock title%}
{% block subnav %}{% include "virtual_nav.html" %}{% endblock subnav %}
{% block content %}
{% if dstore_list %}
    <h2>{{dstore_list|length}} Datastores</h2>
    <table>
	<tr BGCOLOR="#cccccc"><td>System Name</td><td>Capacity</td><td>Free Space</td><td>Used Space</td></tr>
    {% for object in dstore_list %}
    <tr class="{% cycle 'row1' 'row2' %}">
		  <td><a href="{% url datastore object.id%}">{{ object.name }}</a></td>
		  <td>{{ object.capacityMB }}</td><td>{{ object.freespaceMB }}</td><td><div style="width:{{ object.percentUtilized }}%;background:orange;">&nbsp;</div></td>
		</tr>		
    {% endfor %}
    </table>
{% else %}
    <p>No Virtual Machines are available.</p>
{% endif %}

{% endblock content%}

trunk/inventory/templates/host.html
{% extends "base.html" %}
{% block title %}VMHost Detail{% endblock title %}
{% block content %}

<h1>{{ vmhost.name }}</h1>
<small>Host</small>

<table>
<tr><th>Property</th><th>Value</th></tr>
<tr><td>Name</td><td>{{ vmhost.name }}</td></tr>
<tr><td>vendor</td><td><a href="{{vmhost.manufacturer.website}}">{{ vmhost.manufacturer }}</a></td></tr>
<tr><td>model</td><td>{{ vmhost.model }}</td></tr>
<tr><td>cpuCount</td><td>{{ vmhost.cpuCount }}</td></tr>
<tr><td>cpuTotal</td><td>{{ vmhost.cpuTotal }}</td></tr>
<tr><td>cpuUsage</td><td>{{ vmhost.cpuUsage }}</td></tr>
<tr><td>Virtual Machines</td>
    <td><ul>{% for vm in vmhost.virtualmachine_set.all %}
        <li><a href="{% url  vm-detail vm.id%}">{{ vm.name }}</a></li>{% endfor %}</ul
	</td></tr>
<tr><td>processor</td><td>{{ vmhost.processor}}</td></tr>
<tr><td></td><td align="right"><small>Last modified ({{vmhost.created|date:"Y:z g:i a"}})</small></td></tr>
</table>

{% endblock content %}

trunk/inventory/templates/index.html
{% extends "base.html" %}

{% load pagination_tags %}
{% block title %}Virtual Machines{% endblock title%}
 
{% block content %}
  <script language="javascript" type="text/javascript" src="/site_media/js/jquery-1.7.1.js"></script>
	<script language="javascript" type="text/javascript" src="/site_media/js/jquery.flot.js"></script>
  <script language="javascript" type="text/javascript" src="/site_media/js/jquery.flot.pie.js"></script>
  <style type="text/css">
		div.graph{width: 56em;height: 300px;}
		label{display: block;padding-left: 1em;}
	</style>
<div id="default" class="graph">Graph goes here</div>

 {% load pagination_tags %}
{% if server_list %}
    <h2>{{server_list|length}} Servers</h2>
    <table>
	<tr BGCOLOR="#cccccc"><td>Server Name</td><td>Memory MB</td><td>CPUs</td></tr>
    {% for object in server_list %}
        <tr class="{% cycle 'row1' 'row2' %}">
		  <td><a href="{% url server-detail object.id%}">{{ object.name }}</a></td>
		  <td>{{ object.capacityMB }}</td><td>{{ object.cpuCount }}</td>
		</tr>
    {% endfor %}
    </table>
{% else %}
    <!-- <p>No Servers are available.</p>-->
{% endif %}

{% if vendor_list %}
    <h2>{{vendor_list|length}} Vendors</h2>
    <table>
	<tr BGCOLOR="#cccccc"><td>Vendor Name</td></tr>
    {% for object in vendor_list %}
        <tr class="{% cycle 'row1' 'row2' %}">
		  <td>
		  {% if object.website %}
			<a href="{{ object.website }}" target="new">{{ object.name }}</a>
		  {% else %}
		    {{ object.name }}
		  {% endif %}
		  </td>
		</tr>
    {% endfor %}
    </table>
{% else %}
    <!-- <p>No vendors are available.</p>-->
{% endif %}


<script type="text/javascript">
$(function () {
	// data
	var data = [];
	var series = Math.floor(Math.random()*10)+1;
	for( var i = 0; i<series; i++)
	{
		data[i] = { label: "Series"+(i+1), data: Math.floor(Math.random()*100)+1 }
	}	
	// GRAPH 8
	$.plot($("#default"), data, 
	{
		series: {
			pie: { 
				show: true,
				radius:395,
				label: {
					show: true,
					formatter: function(label, series){
						return '<div style="font-size:8pt;text-align:center;padding:2px;color:white;">'+label+'<br/>'+Math.round(series.percent)+'%</div>';
					},
					threshold: 0.1
				}
			}
		},
		legend: {
			show: false
		}
	});
});
</script>

{% endblock content%}

trunk/inventory/templates/newServer.html
{% extends "base.html" %}

{% block content%}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url newServer %}" method="post">{% csrf_token %}
{{ form.as_p }}
<td rowspan=2><input type="submit" value="Submit" />
</form>
{% endblock content%}

trunk/inventory/templates/server_detail.html
{% extends "base.html" %}
{% block title %}Server Detail{% endblock title %}
{% block content %}

<h1>{{ server.name }}</h1>
<small>Server</small>

<table>
<tr><th>Property</th><th>Value</th></tr>
<tr><td>Name</td><td>{{ server.name }}</td></tr>
<tr><td>Vendor</td><td>{{ server.vendor }}</td></tr>
<tr><td>CPU count</td><td>{{ server.cpuCount }}</td></tr>
<tr><td>Capacity MB</td><td>{{ server.capacityMB }}</td></tr>
<tr><td>Notes</td><td>{{ server.notes }}</td></tr>
<tr><td>Purchased</td><td>{{server.purchased}}</td></tr>
<tr><td></td><td align="right"><small>modified ({{server.created|date:"Y:z g:i a"}})</small></td></tr>
</table>

{% endblock content %}

trunk/inventory/templates/server_edit.html
{% extends "base.html" %}

{% block content%}
<h2>edit</h2>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url edit-server server_id %}" method="post">{% csrf_token %}
{{ form.as_p }}
<td rowspan=2><input type="submit" value="Submit" />
</form>
{% endblock content%}

trunk/inventory/templates/server_list.html
{% extends "base.html" %}

{% load pagination_tags %}
{% block title %}Virtual Machines{% endblock title%}
 {% block subnav %}<a href="{% url new-server %}">new server</a>{% endblock subnav %}
{% block content %}
 {% load pagination_tags %}
{% if server_list %}
    <h2>{{server_list|length}} Servers</h2>
    <table>
	<tr BGCOLOR="#cccccc"><td>Server Name</td><td>Memory MB</td><td>CPUs</td></tr>
    {% for object in server_list %}
        <tr class="{% cycle 'row1' 'row2' %}">
		  <td><a href="{% url server-detail object.id%}">{{ object.name }}</a></td>
		  <td>{{ object.capacityMB }}</td><td>{{ object.cpuCount }}</td>
		</tr>
    {% endfor %}
    </table>
{% else %}
    <p>No Servers are available.</p>
{% endif %}
{% endblock content %}

trunk/inventory/templates/virtual_nav.html
<a href="{% url host-list %}">vm hosts</a>
<a href="{% url datastore-list %}">data stores</a>

trunk/inventory/templates/vm_detail.html
{% extends "base.html" %}
{% block title %}Virtual Machine Detail{% endblock title %}
{% block subnav %}{% include "virtual_nav.html" %}{% endblock subnav %}
{% block content %}

<h1>{{ vm.name }}</h1>
<small>Virtual Machine</small>

<table>
<tr><th>Property</th><th>Value</th></tr>
<tr><td>Name</td><td>{{ vm.name }}</td></tr>
<tr><td>Powered ON</td><td class="{{ vm.powerState|yesno:"on,off,unknown" }}"><!--{{ vm.powerState }}--></td></tr>
<tr><td>CPU count</td><td>{{ vm.cpuCount }}</td></tr>
<tr><td>MB of Memory</td><td>{{ vm.memoryMB }}</td></tr>
<tr><td>Notes</td><td>{{ vm.notes }}</td></tr>
<tr><td>IP</td><td><ul>{% for ip in vm.ipaddress_set.all %}<li>{{ ip.address|slice:"8:" }}</li>{% endfor %}</ul</td></tr>
<tr><td>DataStore</td><td>
    <ul>
    {% for ds in vm.datastore.all %}
	<li><a href="{% url datastore ds.id %}" >{{ ds.name }}</a></li>
	{% endfor %}
	</ul>
	</td></tr>
<tr><td>Host</td><td><a href="{% url host vm.host_id %}">{{vm.host}}</a></td></tr>
<tr><td></td><td align="right"><small>modified ({{vm.created|date:"Y:z g:i a"}})</small></td></tr>
</table>

{% endblock content %}

trunk/inventory/templates/vm_list.html
{% extends "base.html" %}

{% load pagination_tags %}
{% block title %}Virtual Machines{% endblock title%}
{% block subnav %}{% include "virtual_nav.html" %}{% endblock subnav %}
{% block content %}
{% if vm_list %}
    <h2>{{vm_list|length}} Virtual Machines</h2>
    {% autopaginate vm_list 25 %}
    <table>
	<tr BGCOLOR="#cccccc"><td>System Name</td><td>Memory MB</td><td>CPUs</td><td>Power State</td></tr>
    {% for object in vm_list %}
        <tr class="{% cycle 'row1' 'row2' %}">
		  <td><a href="{% url vm-detail object.id%}">{{ object.name }}</a></td>
		  <td>{{ object.memoryMB }}</td><td>{{ object.cpuCount }}</td>
		  <td class="{{ object.powerState|yesno:"on,off,unknown" }}"><!--{{object.powerState}}--></td>
		</tr>
    {% endfor %}
    </table>
    {% paginate %}
{% else %}
    <p>No Virtual Machines are available.</p>
{% endif %}

{% endblock content%}